env:
  global:
    # Used for saving generated test datasets. See Notion for details.
    - secure=bP5CEyBsybJUx+iBxZ4XKoMPHd2iMdYVhTNNcVSSPUvLLjmLYVDkbH7b4tD9vN+3i/5pCs+m3sfq0iuQHsP8l7D4VsouB+3jt81gw59o8bpVuTpse0jmagoxsw3TvU3Mu/felE3loBz+BbRkpDCnTZHYn0fAd95Xk3es1iex0zs+fmk4ClYg2yzrtVRw972j0/wMWWXs+Phw2dhB9Mx5fHtm9zV6RoMndBWiq3vwdqGTOoBLoILJ0mQbkMA1SuILPQDN2DtCsBIFTRoH9DI+KUyTzPcvrTUZoMTpVa/09Vpb2cZAhzH9S0++bGs1Ib9m8rrnUyaQk/iJRYxEj9DcCvYpO7TypS13E69CfggCdI5EE5TKs1LBr8wkGMp8ajzh3qMEotF+9QMJkeyqqX5roV/kzB5HV2yqzJSD8aAdHxDw4VYfj312884DDanQh/RXeF8sg5+k8KBx6vjZOhONk5/pzvSR1FTS63+KCI1XHP/kWiDpHg215KekmUQg+SxZUFMqZN+8SL609F+TZqQt5s2uK2Gr/hSCUWY/KmeiLc83PGSSYw59E34CcADBysbJ0lueiPzDybOIAB1hcKHIF5pIANzPCocLmK0axGbp90fN85tcgDCY5axEwJ7s8Uw+h4kTi1HhPfap19I/9EMVrpML+vB+kTSNLFuMVV7keP4=
    - APPLICATION=ops

dist: focal
os: linux
language: php
python:
  - 3.3 # Required by Javascript linter/builder
git:
  # Inhibit automatic submodule checkout
  submodules: false
cache:
  npm: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache
addons:
  chrome: beta
  postgresql: "9.5"
  apt:
    update: true
    packages:
      - libvulkan1
      - libu2f-udev

before_install:
  # MariaDB has conflicts with MySQL, given that Travis includes MySQL by default, we have to uninstall it before installing MariaDB
  - |
    if [[ "$TEST" == "mariadb" ]]; then
      sudo apt-get remove --purge mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-*
      sudo apt-get autoremove -y
      sudo apt-get autoclean
      sudo rm -rf /var/lib/mysql/
      sudo rm -rf /etc/mysql/
      sudo apt-get install mariadb-server mariadb-client
    fi
  - if [ -n "$LIBONIG_INSTALL" ]; then sudo apt-get install libonig5; fi
  - ./tools/startSubmodulesTRAVIS.sh
  - npm i g -npm
  - ./lib/pkp/tools/travis/prepare-webserver.sh
  - ./lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm install && npm run build

stages:
  - validate
  - test
  - upgrade

jobs:
  include:
    - stage: test
      env: TEST=pgsql SAVE_BUILD=true
      php: 8.1.0
    - env: TEST=mariadb SAVE_BUILD=true
      php: 8.1.0
    - env: TEST=mysql SAVE_BUILD=true
      php: 8.1.0
    - env: TEST=mysql LIBONIG_INSTALL=1
      php: 8.2.0
    - env: TEST=pgsql LIBONIG_INSTALL=1
      php: 8.2.0

    - stage: validate
      php: 8.1.0
      name: "Validate and lint"
      script:
      - |
        npm install
        ./lib/pkp/tools/travis/install-linter.sh
        ./lib/pkp/tools/travis/validate-xml.sh
        ./lib/pkp/tools/buildjs.sh -n
        ./lib/pkp/tools/checkHelp.sh
        ./lib/pkp/tools/travis/validate-json.sh
        npm run lint

    - stage: upgrade
      env: DATASET_BRANCH=stable-3_4_0 TEST=mysql
      php: 8.1.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - source ./lib/pkp/tools/travis/migration/v3_4_0/prepare-logs.sh
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - stage: upgrade
      env: DATASET_BRANCH=stable-3_3_0 TEST=mysql
      php: 8.1.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - source ./lib/pkp/tools/travis/migration/v3_4_0/prepare-logs.sh
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=stable-3_4_0 TEST=pgsql
      php: 8.1.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - source ./lib/pkp/tools/travis/migration/v3_4_0/prepare-logs.sh
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=stable-3_3_0 TEST=pgsql
      php: 8.1.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - source ./lib/pkp/tools/travis/migration/v3_4_0/prepare-logs.sh
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

script:
  - source ./lib/pkp/tools/travis/prepare-tests.sh
  - ./lib/pkp/tools/travis/run-tests.sh

after_failure:
  - tail -n 500 error.log
  - sudo apt-get install sharutils
  # Outputs only the oldest file found at the screenshots folder due to log limits
  - find cypress/screenshots -type f -printf '%T+\t%p\n' | sort | head -n 1 | cut -f 2 | tar -czT - | uuencode /dev/stdout

after_success:
  - head -n 500 error.log
