on: [push, pull_request]
name: main
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database: ['mysql','mariadb','pgsql']
        php-version: [ '8.1' ,'8.2']


    name: main
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
